### ISSUE TITLE
镜像拉取下来后，访问vnc报错 

### ISSUE THREAD

**Issue by dgo2dance** [ChisBread/wechat-box#4]
## 镜像拉取下来后，访问vnc报错 
noVNC encountered an error:
noVNC 遇到错误：

Uncaught TypeError: WebUtil.fetchJSON is not a function
未捕获的类型错误：WebUtil.fetchJSON 不是函数
http://localhost:8080/app/ui.js:1656:13
TypeError: WebUtil.fetchJSON is not a function
    at http://localhost:8080/app/ui.js:1656:13
类型错误：WebUtil.fetchJSON 不是函数
    在 http://localhost:8080/app/ui.js:1656:13

**Comment by dgo2dance** [comment]
> ## 镜像拉取下来后，访问vnc报错
> noVNC encountered an error:noVNC 遇到错误： noVNC 遇到错误：
> 
> Uncaught TypeError: WebUtil.fetchJSON is not a function未捕获的类型错误：WebUtil.fetchJSON 不是函数 未捕获的类型错误：WebUtil.fetchJSON 不是函数 http://localhost:8080/app/ui.js:1656:13 TypeError: WebUtil.fetchJSON is not a function类型错误：WebUtil.fetchJSON 不是函数 at http://localhost:8080/app/ui.js:1656:13 类型错误：WebUtil.fetchJSON 不是函数 在 http://localhost:8080/app/ui.js:1656:13

换成ip访问后可以了  如何启动微信登录呢？

**Comment by ChisBread** [comment]
> > ## 镜像拉取下来后，访问vnc报错
> > noVNC encountered an error:noVNC 遇到错误： noVNC 遇到错误：
> > Uncaught TypeError: WebUtil.fetchJSON is not a function未捕获的类型错误：WebUtil.fetchJSON 不是函数 未捕获的类型错误：WebUtil.fetchJSON 不是函数 http://localhost:8080/app/ui.js:1656:13 TypeError: WebUtil.fetchJSON is not a function类型错误：WebUtil.fetchJSON 不是函数 at http://localhost:8080/app/ui.js:1656:13 类型错误：WebUtil.fetchJSON 不是函数 在 http://localhost:8080/app/ui.js:1656:13
> 
> 换成ip访问后可以了 如何启动微信登录呢？

看看docker日志，微信一般是自动开启的
